name: Build, Test, and Dockerize

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: docker build -t sample-node-app .
      
      # - name: Push image
      #   if: github.event_name == 'push'
      #   run: |
      #     docker tag sample-node-app avinashnagula/sample-node-app:latest
      #     docker push avinashnagula/sample-node-app:latest

      # Optional: Push to Docker Hub
      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push image
        if: github.event_name == 'push'
        run: |
          docker tag sample-node-app ${{ secrets.DOCKER_USERNAME }}/sample-node-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/sample-node-app:latest


